# Generated by Django 5.2.8 on 2025-12-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
