# Generated by Django 4.2 on 2025-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/default.jpg",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
