# Generated by Django 5.2.8 on 2025-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_breif_description_alter_product_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="especial",
            field=models.BooleanField(default=False),
        ),
    ]
