# Generated by Django 5.2.8 on 2025-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_especial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
