# Generated by Django 5.2.8 on 2025-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'خانه'), ('office', 'محل کار'), ('other', 'سایر')], default='home', max_length=200, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=200, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(max_length=200, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('payment_verified', 'پرداخت تایید شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=200, verbose_name='وضعیت سفارش'),
        ),
    ]
