# Generated by Django 5.2.8 on 2025-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="فرمت\u200cهای مجاز: mp4, mkv, avi",
                null=True,
                upload_to="blog/videos/",
            ),
        ),
    ]
